### PR TITLE
change return in gradient kernel

### PR DESCRIPTION
**Pull request by modichirag**
Issue: for N>63, the output of nbody was equal = 1 over whole mesh.
Cause: gradient kernel returned 0s for order=1, hence the initial displacements in 'lpt1=0'
Fix: "return wts[:]" instead of "return wts"
(underlying cause is not completely understood yet)

### CODE REVIEW

**Comment by EiffL** [comment]
Feel free to click the  big merge button!

**Comment by modichirag** [comment]
Closes: #4

**Comment by modichirag** [comment]
Closes: #4

**Comment by EiffL** [comment]
Yeah ! Passes the tests, feel free to merge :-D

**Pull request merged**
