### PR TITLE
Functions to compute the distances

### PR DESCRIPTION
**Pull request by dlanzieri**
I implemented the function to compute the comoving distance and the function to compute the scale factor from  coming values useful to implement the raytracing.

### CODE REVIEW

**Comment by EiffL** [comment]
@dlanzieri can you let me know what test is failing exactly?

**Comment by EiffL** [comment]
So, I notice the tests are not working because you use jax-cosmo and that it's not currently included as a dependency of the package. 

So, we want to remove any reference to jax-cosmo, and instead try to use the `nobdykit` library that is already a dependency of the package.

An nbodykit cosmology object should have a `comoving_distance` method.

**Comment by EiffL** [comment]
@dlanzieri did you solve these issues with tests? Did you find the nbodykit function for distances?

**Comment by EiffL** [comment]
I hear you made some progress on this :-) could you upload your latest code? If we want to meet our target of having lensing maps by the end of the week, we will probably need to merge distances tomorrow morning, I can have a look to see if I can help.

**Comment by EiffL** [comment]
Fantastic! Thanks, I'm gonna have a look a this, but it looks really good already!

**Comment by EiffL** [comment]
I found the problem ^^' have a look at: 
 https://github.com/modichirag/flowpm/pull/60/commits/3fdc468a054d7ec5828bbda46368ef4af2546e30

Turned out the 2 "Planck15" cosmologies were not exacly the same, and the differences were enough to cause the tests to fail.

It's looking good now, and your code was correct :-) Feel free to turn this draft PR into a full PR

**Comment by dlanzieri** [comment]
@EiffL Fantastic, thank you!!

**Comment by EiffL** [comment]
Ah ^^' I see that you merged this @dlanzieri ... But the pull request had not been reviewed yet :-| 

It's ok for this time, but just to let you know, a good practice is not to merge anything into master until somebody else had a chance to do a proper review and validate the PR.

The review process can take a little time, but in most cases you don't have to wait for your pr to be merged in master to start working on the next thing. For instance you can create a new branch based on this branch, and make new modifications to it.

**Comment by dlanzieri** [comment]
@EiffL I'm really sorry, these are my first steps on GitHub and I have much to learn. It won't happen again!

**Comment by EiffL** [comment]
Don't worry ^^' it's just to let you know. And in general, don't worry, you can't break anything on GitHub ;-) In worst case scenarios, there is a button to undo a merge:
image
But as I said, for this one it's ok :-) It's just to talk about best practices

**Pull request merged**
